name: bundled

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-bundled:
    name: bundled (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build and run bundled static smoke test
        run: cargo run -p libopus_sys_bundled --features bundled,static


